export interface LineItem {
  description: string;
  unit: string;
  rate: string;
}

export interface Profession {
  slug: string;
  name: string;
  plural: string;
  emoji: string;
  category: string;
  lineItems: LineItem[];
  paymentTerms: string;
  avgRates: { label: string; range: string }[];
  lateFeeNote: string;
  paymentNorm: string;
}

export const professions: Profession[] = [
  {
    slug: "graphic-designer",
    name: "Graphic Designer",
    plural: "Graphic Designers",
    emoji: "🎨",
    category: "Creative",
    lineItems: [
      { description: "Logo design (primary + variations)", unit: "project", rate: "$800.00" },
      { description: "Brand style guide", unit: "project", rate: "$400.00" },
      { description: "Social media graphics (10-pack)", unit: "pack", rate: "$250.00" },
      { description: "Rush fee (48hr turnaround)", unit: "flat", rate: "$150.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$35–$150/hr" },
      { label: "Logo package", range: "$300–$2,500" },
      { label: "Brand identity", range: "$1,000–$10,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Graphic designers typically collect 50% upfront, 50% on delivery. Net 14 is standard for ongoing clients.",
  },
  {
    slug: "web-designer",
    name: "Web Designer",
    plural: "Web Designers",
    emoji: "💻",
    category: "Creative",
    lineItems: [
      { description: "Website design (up to 5 pages)", unit: "project", rate: "$2,500.00" },
      { description: "Mobile responsive optimization", unit: "project", rate: "$500.00" },
      { description: "Content upload & formatting", unit: "hr", rate: "$75.00" },
      { description: "Revisions (beyond 2 rounds)", unit: "hr", rate: "$90.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$50–$200/hr" },
      { label: "5-page website", range: "$1,500–$8,000" },
      { label: "E-commerce site", range: "$3,000–$20,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Web designers typically collect 30–50% deposit before work begins, with remaining balance due on launch.",
  },
  {
    slug: "photographer",
    name: "Photographer",
    plural: "Photographers",
    emoji: "📷",
    category: "Creative",
    lineItems: [
      { description: "Photo shoot (2 hours)", unit: "session", rate: "$400.00" },
      { description: "Photo editing & retouching (20 photos)", unit: "batch", rate: "$200.00" },
      { description: "Travel fee (>30km)", unit: "flat", rate: "$75.00" },
      { description: "Additional edited photos", unit: "each", rate: "$15.00" },
    ],
    paymentTerms: "Due on delivery",
    avgRates: [
      { label: "Portrait session", range: "$150–$500" },
      { label: "Wedding photography", range: "$1,500–$5,000" },
      { label: "Commercial shoot", range: "$500–$3,000/day" },
    ],
    lateFeeNote: "Late payment fee of $50 applies after 7 days past due date.",
    paymentNorm: "Photographers typically require full payment before gallery delivery. A deposit secures the date.",
  },
  {
    slug: "videographer",
    name: "Videographer",
    plural: "Videographers",
    emoji: "🎬",
    category: "Creative",
    lineItems: [
      { description: "Filming (half-day, 4 hours)", unit: "session", rate: "$800.00" },
      { description: "Video editing & color grading", unit: "hr", rate: "$100.00" },
      { description: "Motion graphics / titles", unit: "flat", rate: "$300.00" },
      { description: "Licensed music", unit: "track", rate: "$50.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$75–$250/hr" },
      { label: "Promo video (2 min)", range: "$1,000–$5,000" },
      { label: "Wedding videography", range: "$1,500–$6,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Videographers typically require a 50% deposit, with remainder due upon final video delivery.",
  },
  {
    slug: "illustrator",
    name: "Illustrator",
    plural: "Illustrators",
    emoji: "✏️",
    category: "Creative",
    lineItems: [
      { description: "Custom illustration (full color)", unit: "each", rate: "$350.00" },
      { description: "Character design", unit: "character", rate: "$500.00" },
      { description: "Spot illustrations (black & white)", unit: "each", rate: "$150.00" },
      { description: "Commercial licensing fee", unit: "flat", rate: "$200.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$40–$150/hr" },
      { label: "Book illustration", range: "$2,000–$10,000" },
      { label: "Character design", range: "$300–$2,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances. Files not released until payment is received.",
    paymentNorm: "Illustrators typically hold final files until payment is cleared. A 30% deposit starts the project.",
  },
  {
    slug: "copywriter",
    name: "Copywriter",
    plural: "Copywriters",
    emoji: "📝",
    category: "Creative",
    lineItems: [
      { description: "Website copy (homepage)", unit: "page", rate: "$600.00" },
      { description: "Email sequence (5 emails)", unit: "sequence", rate: "$750.00" },
      { description: "Landing page copy", unit: "page", rate: "$500.00" },
      { description: "Revision round (beyond 2)", unit: "round", rate: "$150.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$50–$200/hr" },
      { label: "Sales page", range: "$500–$5,000" },
      { label: "Email sequence (5)", range: "$500–$2,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Copywriters typically collect 50% upfront. Net 14 is standard for ongoing retainer clients.",
  },
  {
    slug: "content-writer",
    name: "Content Writer",
    plural: "Content Writers",
    emoji: "✍️",
    category: "Creative",
    lineItems: [
      { description: "Blog post (1,000–1,500 words)", unit: "post", rate: "$150.00" },
      { description: "SEO optimization & keyword research", unit: "post", rate: "$50.00" },
      { description: "Social media captions (10 posts)", unit: "pack", rate: "$100.00" },
      { description: "Rush delivery (<48hrs)", unit: "surcharge", rate: "$75.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Per word rate", range: "$0.05–$0.50/word" },
      { label: "Blog post (1,000 words)", range: "$75–$500" },
      { label: "Monthly retainer", range: "$500–$3,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Content writers on retainer typically invoice monthly. Project-based: Net 14 after delivery.",
  },
  {
    slug: "social-media-manager",
    name: "Social Media Manager",
    plural: "Social Media Managers",
    emoji: "📱",
    category: "Creative",
    lineItems: [
      { description: "Monthly social media management (3 platforms)", unit: "month", rate: "$1,200.00" },
      { description: "Content creation (20 posts/month)", unit: "month", rate: "$600.00" },
      { description: "Analytics report & strategy call", unit: "month", rate: "$150.00" },
      { description: "Paid ads management", unit: "month", rate: "$400.00" },
    ],
    paymentTerms: "Net 7",
    avgRates: [
      { label: "Monthly retainer", range: "$500–$5,000/mo" },
      { label: "Per platform", range: "$300–$1,500/mo" },
      { label: "Ad management fee", range: "$300–$1,000/mo" },
    ],
    lateFeeNote: "Services paused if invoice is more than 7 days overdue.",
    paymentNorm: "Social media managers typically invoice monthly in advance. Payment due before the month starts.",
  },
  {
    slug: "freelance-developer",
    name: "Freelance Developer",
    plural: "Freelance Developers",
    emoji: "⌨️",
    category: "Tech",
    lineItems: [
      { description: "Development work", unit: "hr", rate: "$120.00" },
      { description: "Code review & QA", unit: "hr", rate: "$100.00" },
      { description: "Technical documentation", unit: "hr", rate: "$90.00" },
      { description: "Deployment & DevOps setup", unit: "flat", rate: "$300.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$75–$250/hr" },
      { label: "Junior developer", range: "$40–$80/hr" },
      { label: "Senior developer", range: "$100–$250+/hr" },
    ],
    lateFeeNote: "1.5% per month on overdue balances. Code ownership transfers on full payment.",
    paymentNorm: "Developers typically bill bi-weekly or monthly for ongoing work. Projects use 50% upfront.",
  },
  {
    slug: "web-developer",
    name: "Web Developer",
    plural: "Web Developers",
    emoji: "🌐",
    category: "Tech",
    lineItems: [
      { description: "Frontend development", unit: "hr", rate: "$110.00" },
      { description: "Backend API development", unit: "hr", rate: "$130.00" },
      { description: "Bug fixes & maintenance", unit: "hr", rate: "$100.00" },
      { description: "Hosting setup & configuration", unit: "flat", rate: "$250.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$60–$200/hr" },
      { label: "Simple website", range: "$1,000–$5,000" },
      { label: "Web app", range: "$5,000–$50,000+" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Web developers use milestone billing for large projects. Ongoing work billed monthly Net 14.",
  },
  {
    slug: "app-developer",
    name: "App Developer",
    plural: "App Developers",
    emoji: "📱",
    category: "Tech",
    lineItems: [
      { description: "Mobile app development", unit: "hr", rate: "$150.00" },
      { description: "UI/UX implementation", unit: "hr", rate: "$120.00" },
      { description: "App Store submission & setup", unit: "flat", rate: "$400.00" },
      { description: "Bug fixes (post-launch)", unit: "hr", rate: "$130.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$75–$250/hr" },
      { label: "Simple app", range: "$5,000–$20,000" },
      { label: "Complex app", range: "$20,000–$100,000+" },
    ],
    lateFeeNote: "1.5% per month on overdue balances. Source code held until final payment.",
    paymentNorm: "App developers typically use milestone billing: 30% upfront, 40% mid-project, 30% on delivery.",
  },
  {
    slug: "data-analyst",
    name: "Data Analyst",
    plural: "Data Analysts",
    emoji: "📊",
    category: "Tech",
    lineItems: [
      { description: "Data analysis & reporting", unit: "hr", rate: "$100.00" },
      { description: "Dashboard creation (Power BI / Tableau)", unit: "flat", rate: "$800.00" },
      { description: "Data cleaning & preparation", unit: "hr", rate: "$80.00" },
      { description: "Presentation & insights summary", unit: "flat", rate: "$300.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$60–$175/hr" },
      { label: "Monthly retainer", range: "$2,000–$8,000/mo" },
      { label: "One-time analysis", range: "$500–$5,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Data analysts often work on retainer. Project work billed Net 14 after delivery.",
  },
  {
    slug: "it-consultant",
    name: "IT Consultant",
    plural: "IT Consultants",
    emoji: "🖥️",
    category: "Tech",
    lineItems: [
      { description: "IT consultation & assessment", unit: "hr", rate: "$150.00" },
      { description: "Network setup & configuration", unit: "flat", rate: "$500.00" },
      { description: "Security audit", unit: "flat", rate: "$1,200.00" },
      { description: "Ongoing support (monthly)", unit: "month", rate: "$800.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$75–$250/hr" },
      { label: "Monthly retainer", range: "$500–$5,000/mo" },
      { label: "Project-based", range: "$1,000–$20,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "IT consultants often invoice monthly for managed services. Project work: Net 14.",
  },
  {
    slug: "consultant",
    name: "Consultant",
    plural: "Consultants",
    emoji: "💼",
    category: "Professional Services",
    lineItems: [
      { description: "Strategic consultation", unit: "hr", rate: "$200.00" },
      { description: "Workshop facilitation (half-day)", unit: "session", rate: "$1,500.00" },
      { description: "Written report & recommendations", unit: "flat", rate: "$1,000.00" },
      { description: "Follow-up support", unit: "hr", rate: "$175.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$100–$500+/hr" },
      { label: "Day rate", range: "$800–$4,000/day" },
      { label: "Monthly retainer", range: "$2,000–$15,000/mo" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Consultants typically require 50% upfront for project work. Retainer invoiced monthly in advance.",
  },
  {
    slug: "marketing-consultant",
    name: "Marketing Consultant",
    plural: "Marketing Consultants",
    emoji: "📣",
    category: "Professional Services",
    lineItems: [
      { description: "Marketing strategy & audit", unit: "flat", rate: "$1,500.00" },
      { description: "Campaign planning", unit: "hr", rate: "$150.00" },
      { description: "Monthly marketing management", unit: "month", rate: "$2,500.00" },
      { description: "Analytics & reporting", unit: "month", rate: "$400.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$75–$300/hr" },
      { label: "Monthly retainer", range: "$1,500–$8,000/mo" },
      { label: "Campaign management", range: "$1,000–$5,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Marketing consultants on retainer invoice monthly in advance. Project work: 50% upfront.",
  },
  {
    slug: "business-consultant",
    name: "Business Consultant",
    plural: "Business Consultants",
    emoji: "📈",
    category: "Professional Services",
    lineItems: [
      { description: "Business analysis & assessment", unit: "flat", rate: "$2,000.00" },
      { description: "Process improvement consulting", unit: "hr", rate: "$200.00" },
      { description: "Business plan development", unit: "flat", rate: "$3,000.00" },
      { description: "Implementation support", unit: "hr", rate: "$175.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$100–$400/hr" },
      { label: "Day rate", range: "$1,000–$5,000/day" },
      { label: "Project retainer", range: "$5,000–$50,000" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Business consultants require 30–50% upfront for projects. Retainer billed monthly in advance.",
  },
  {
    slug: "accountant",
    name: "Accountant",
    plural: "Accountants",
    emoji: "🧮",
    category: "Professional Services",
    lineItems: [
      { description: "Tax return preparation (personal)", unit: "return", rate: "$300.00" },
      { description: "Tax return preparation (business)", unit: "return", rate: "$800.00" },
      { description: "Monthly bookkeeping", unit: "month", rate: "$400.00" },
      { description: "Financial statement preparation", unit: "flat", rate: "$600.00" },
    ],
    paymentTerms: "Due on delivery",
    avgRates: [
      { label: "Hourly rate", range: "$50–$300/hr" },
      { label: "Personal tax return", range: "$150–$600" },
      { label: "Business tax return", range: "$500–$3,000+" },
    ],
    lateFeeNote: "1.5% per month on overdue balances. Files not released until payment is received.",
    paymentNorm: "Accountants typically collect payment before releasing tax filings or financial documents.",
  },
  {
    slug: "bookkeeper",
    name: "Bookkeeper",
    plural: "Bookkeepers",
    emoji: "📚",
    category: "Professional Services",
    lineItems: [
      { description: "Monthly bookkeeping (up to 100 transactions)", unit: "month", rate: "$350.00" },
      { description: "Bank reconciliation", unit: "month", rate: "$100.00" },
      { description: "Payroll processing (up to 5 employees)", unit: "month", rate: "$200.00" },
      { description: "Catch-up bookkeeping (per month)", unit: "month", rate: "$250.00" },
    ],
    paymentTerms: "Net 7",
    avgRates: [
      { label: "Hourly rate", range: "$20–$75/hr" },
      { label: "Monthly retainer", range: "$200–$2,000/mo" },
      { label: "Catch-up bookkeeping", range: "$150–$400/mo" },
    ],
    lateFeeNote: "Services suspended if invoice is more than 7 days overdue.",
    paymentNorm: "Bookkeepers invoice monthly. Payment due within 7 days to maintain service continuity.",
  },
  {
    slug: "virtual-assistant",
    name: "Virtual Assistant",
    plural: "Virtual Assistants",
    emoji: "🤝",
    category: "Professional Services",
    lineItems: [
      { description: "Virtual assistant services", unit: "hr", rate: "$35.00" },
      { description: "Email management (monthly)", unit: "month", rate: "$300.00" },
      { description: "Calendar & scheduling", unit: "month", rate: "$200.00" },
      { description: "Research & data entry", unit: "hr", rate: "$30.00" },
    ],
    paymentTerms: "Net 7",
    avgRates: [
      { label: "Hourly rate", range: "$15–$75/hr" },
      { label: "Monthly retainer (20hrs)", range: "$400–$1,500/mo" },
      { label: "Specialty VA (tech)", range: "$40–$100/hr" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 7 days.",
    paymentNorm: "VAs typically invoice weekly or monthly. Prepaid retainers are common for ongoing work.",
  },
  {
    slug: "personal-trainer",
    name: "Personal Trainer",
    plural: "Personal Trainers",
    emoji: "💪",
    category: "Trades & Other",
    lineItems: [
      { description: "Personal training session (1 hour)", unit: "session", rate: "$80.00" },
      { description: "Custom workout program", unit: "program", rate: "$150.00" },
      { description: "Nutrition plan", unit: "plan", rate: "$100.00" },
      { description: "Monthly online coaching", unit: "month", rate: "$200.00" },
    ],
    paymentTerms: "Due on service",
    avgRates: [
      { label: "Per session", range: "$50–$200/session" },
      { label: "Monthly package (12 sessions)", range: "$600–$2,400/mo" },
      { label: "Online coaching", range: "$100–$500/mo" },
    ],
    lateFeeNote: "$25 late payment fee applies after 7 days.",
    paymentNorm: "Personal trainers typically require payment before sessions or sell session packs upfront.",
  },
  {
    slug: "tutor",
    name: "Tutor",
    plural: "Tutors",
    emoji: "🎓",
    category: "Trades & Other",
    lineItems: [
      { description: "Tutoring session (1 hour)", unit: "session", rate: "$60.00" },
      { description: "Test prep intensive (3 hours)", unit: "session", rate: "$150.00" },
      { description: "Study materials & worksheets", unit: "flat", rate: "$30.00" },
      { description: "Monthly package (8 sessions)", unit: "package", rate: "$420.00" },
    ],
    paymentTerms: "Due on service",
    avgRates: [
      { label: "Per hour", range: "$25–$150/hr" },
      { label: "Test prep", range: "$50–$200/hr" },
      { label: "Monthly package", range: "$400–$1,200/mo" },
    ],
    lateFeeNote: "$15 late fee after 7 days. Sessions cancelled for outstanding balances.",
    paymentNorm: "Tutors typically collect payment at session time or sell monthly packages paid in advance.",
  },
  {
    slug: "translator",
    name: "Translator",
    plural: "Translators",
    emoji: "🌍",
    category: "Trades & Other",
    lineItems: [
      { description: "Document translation", unit: "per 1,000 words", rate: "$120.00" },
      { description: "Certified translation", unit: "per page", rate: "$75.00" },
      { description: "Rush translation (<24hrs)", unit: "surcharge", rate: "50% extra" },
      { description: "Proofreading & editing", unit: "per 1,000 words", rate: "$60.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Per word", range: "$0.08–$0.25/word" },
      { label: "Per page", range: "$50–$150/page" },
      { label: "Certified translation", range: "$75–$150/page" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Translators typically require payment before delivering final documents. Net 14 for agencies.",
  },
  {
    slug: "event-planner",
    name: "Event Planner",
    plural: "Event Planners",
    emoji: "🎉",
    category: "Trades & Other",
    lineItems: [
      { description: "Event planning & coordination", unit: "event", rate: "$1,500.00" },
      { description: "Vendor sourcing & management", unit: "flat", rate: "$500.00" },
      { description: "Day-of coordination (8 hours)", unit: "day", rate: "$800.00" },
      { description: "Timeline & run-of-show creation", unit: "flat", rate: "$300.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Day-of coordination", range: "$500–$2,000" },
      { label: "Full planning", range: "$1,500–$10,000+" },
      { label: "% of event budget", range: "10–20% of total" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Event planners require 25–50% deposit to hold the date. Remainder due 30 days before the event.",
  },
  {
    slug: "interior-designer",
    name: "Interior Designer",
    plural: "Interior Designers",
    emoji: "🛋️",
    category: "Trades & Other",
    lineItems: [
      { description: "Initial consultation & space assessment", unit: "flat", rate: "$150.00" },
      { description: "Design concept & mood board", unit: "flat", rate: "$800.00" },
      { description: "Full room design (drawings + sourcing)", unit: "room", rate: "$1,500.00" },
      { description: "Project management & installation oversight", unit: "hr", rate: "$125.00" },
    ],
    paymentTerms: "Net 14",
    avgRates: [
      { label: "Hourly rate", range: "$75–$250/hr" },
      { label: "Per room", range: "$500–$5,000" },
      { label: "Full home design", range: "$5,000–$50,000+" },
    ],
    lateFeeNote: "1.5% per month on overdue balances after 14 days.",
    paymentNorm: "Interior designers typically require 50% deposit. Procurement requires full payment in advance.",
  },
  {
    slug: "music-teacher",
    name: "Music Teacher",
    plural: "Music Teachers",
    emoji: "🎵",
    category: "Trades & Other",
    lineItems: [
      { description: "Private lesson (30 minutes)", unit: "lesson", rate: "$40.00" },
      { description: "Private lesson (60 minutes)", unit: "lesson", rate: "$70.00" },
      { description: "Monthly lesson package (4 x 60 min)", unit: "month", rate: "$260.00" },
      { description: "Recital preparation fee", unit: "flat", rate: "$50.00" },
    ],
    paymentTerms: "Due on service",
    avgRates: [
      { label: "Per 30-min lesson", range: "$30–$80" },
      { label: "Per 60-min lesson", range: "$50–$150" },
      { label: "Monthly package", range: "$180–$600/mo" },
    ],
    lateFeeNote: "$20 late fee after 7 days. Lessons cancelled for balances over 14 days.",
    paymentNorm: "Music teachers typically bill monthly in advance or collect per-session. Monthly packages are most common.",
  },
];

export function getProfession(slug: string): Profession | undefined {
  return professions.find((p) => p.slug === slug);
}

export function generateStaticParams() {
  return professions.map((p) => ({ profession: p.slug }));
}
